name: Build and Push (Static App)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:$(git rev-parse --short HEAD)
          docker build -t $IMAGE .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Push
        run: docker push $IMAGE

      - name: Also tag 'latest' (optional)
        run: |
          LATEST=ghcr.io/${{ github.repository }}:latest
          docker tag $IMAGE $LATEST
          docker push $LATEST
